### ISSUE TITLE
Why do you hate me?

### ISSUE THREAD

**Issue by KRONOS-11** [offsetearth/jest-pixel-perfect#1]
This is an intentional evil creation, isn't it?

**Comment by mathieudutour** [comment]
I don't know what you're talking about 😄

**Comment by mathieudutour** [comment]
That's because there is no Sketch support yet? Don't worry it's coming soon

**Comment by macintoshhelper** [comment]
> That's because there is no Sketch support yet? Don't worry it's coming soon

😲 that's on my todo list (with `@skpm/test-runner`).
